In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.22.3


In [18]:
arr = np.array([4,5,6,7], ndmin=6)


In [45]:
print(arr, type(arr), arr.ndim)

[42  2  3  4  5] <class 'numpy.ndarray'> 1


In [27]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[-1, -1])

Last element from 2nd dim:  10


In [36]:
# skipping no of elements
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::3])

[1 4 7]


In [46]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [51]:
# in view, changes will affect the original array
arr = np.array([1, 2, 3, 4, 5])
v = arr.view()
arr[0] = 42

print(arr)
print(v)

[42  2  3  4  5]
[42  2  3  4  5]


In [52]:
# in copy changes will not affect the original array
arr = np.array([1, 2, 3, 4, 5])
c = arr.copy()
arr[0] = 42

print(arr)
print(c)

[42  2  3  4  5]
[1 2 3 4 5]


In [54]:
print(v.base)
print(c.base)

[42  2  3  4  5]
None


In [71]:
arr = np.array([[[1, 2, 3, 4, 5],[1, 2, 3, 4,5],[1, 2, 3, 4,5]]])
print(arr.shape)
print(arr.ndim)
print(arr)

(1, 3, 5)
3
[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]


In [74]:
# 1D to 2D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)
print(newarr.shape)
print(newarr.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
2


In [79]:
# 1D to 3D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)
print(arr.reshape(2, 3, 2).base)
print(newarr)
print(newarr.shape)
print(newarr.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
3


In [82]:
# for iterating high diamention array can use nditer()
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(np.nditer(arr))
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8
